In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
data = np.random.randn(7,4)

In [7]:
data

array([[ 0.89031584, -1.39525782,  1.95547388, -0.96946379],
       [ 0.56595738,  0.13501787,  0.1244155 , -1.04785235],
       [-0.7786109 , -0.48735074,  0.0652928 ,  0.1086246 ],
       [ 1.28016753, -0.7847591 ,  0.5137345 , -0.35918994],
       [-0.11797389, -1.37055049,  1.60191276, -0.65194639],
       [ 1.57689136, -0.88654826,  0.56949389, -1.07007244],
       [-1.07149008,  1.02453706,  1.20602574,  1.84616299]])

In [8]:
data[data<0]=0

In [9]:
data

array([[0.89031584, 0.        , 1.95547388, 0.        ],
       [0.56595738, 0.13501787, 0.1244155 , 0.        ],
       [0.        , 0.        , 0.0652928 , 0.1086246 ],
       [1.28016753, 0.        , 0.5137345 , 0.        ],
       [0.        , 0.        , 1.60191276, 0.        ],
       [1.57689136, 0.        , 0.56949389, 0.        ],
       [0.        , 1.02453706, 1.20602574, 1.84616299]])

In [36]:
arr = np.arange(16).reshape((2,2,4))

In [38]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [16]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [17]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [37]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [40]:
arr = np.arange(10)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [43]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [44]:
arr = np.random.randn(4, 4)

In [45]:
arr

array([[-2.97616323,  1.4729107 ,  1.11755577, -0.90098053],
       [ 1.03928486, -0.23856541,  1.18137603,  1.71606035],
       [ 0.57385274,  0.22530816, -0.19491504, -0.76521828],
       [ 0.28447873, -0.15970835,  0.66688524, -0.30501112]])

In [47]:
np.where(arr>0,2, -2)

array([[-2,  2,  2, -2],
       [ 2, -2,  2,  2],
       [ 2,  2, -2, -2],
       [ 2, -2,  2, -2]])

In [48]:
arr = np.random.randn(100)

In [49]:
(arr > 0).sum()

45